export component ClockWidget inherits Rectangle {
    in property <string> current-time: "00:00";
    in property <string> current-date: "";
    in property <length> time-x: 0px;
    in property <length> time-y: 0px;

    VerticalLayout {
        x: root.time-x;
        y: root.time-y;
        width: 450px;
        alignment: start;
        spacing: 8px;

        Text {
            text: root.current-time;
            color: white;
            font-size: 72px;
            horizontal-alignment: center;
        }

        Text {
            text: root.current-date;
            color: white;
            font-size: 32px;
            horizontal-alignment: center;
        }
    }
}
